'use client';

import { useState } from 'react';
import { BarChart3, FolderGit2, FolderOpen, Github, Plus, X } from 'lucide-react';
import { CompletedRun, DevPilotConfig, Feature, ProjectEntry } from '../../../lib/types';

interface ProjectsViewProps {
  projects: ProjectEntry[];
  selectedProjectId: string;
  selectedDashboardProjectIds: string[];
  onSelectProject: (id: string) => void;
  onToggleDashboardProject: (id: string, selected: boolean) => void;
  onAddProject: (entry: ProjectEntry) => void;
  runHistory: CompletedRun[];
}

export function ProjectsView({
  projects,
  selectedProjectId,
  selectedDashboardProjectIds,
  onSelectProject,
  onToggleDashboardProject,
  onAddProject,
  runHistory,
}: ProjectsViewProps) {
  const [showAddModal, setShowAddModal] = useState(false);
  const [addMode, setAddMode] = useState<'local' | 'github'>('local');
  const [localPath, setLocalPath] = useState('');
  const [githubUrl, setGithubUrl] = useState('');
  const [githubToken, setGithubToken] = useState(() =>
    typeof window !== 'undefined' ? (localStorage.getItem('devpilot-github-token') ?? '') : '',
  );
  const [adding, setAdding] = useState(false);
  const [addError, setAddError] = useState('');
  const [reportText, setReportText] = useState('');
  const [reportCopied, setReportCopied] = useState(false);

  const isTauri = typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;

  const handleAddGitHub = async () => {
    if (!githubUrl.trim()) return;
    setAdding(true);
    setAddError('');
    try {
      const { fetchGithubRepo } = await import('../../../lib/bridge');
      const ghFeatures = await fetchGithubRepo(githubToken, githubUrl);

      const repoName = githubUrl.trim().replace(/\/$/, '').split('/').slice(-2).join('/');
      const features: Feature[] = ghFeatures.map((f) => ({
        id: f.id,
        name: f.name,
        status: f.status as Feature['status'],
        category: f.category,
        progress: f.progress,
        notes: f.notes,
        paths: { spec: '', tdd: '', implementation: '' },
        adapters: [],
      }));

      const config: DevPilotConfig = {
        schemaVersion: 1,
        project: { name: repoName, root: githubUrl.trim(), defaultIDE: 'Cursor' },
        features,
        adapters: { ides: [], agents: [] },
      };

      onAddProject({ id: `gh-${Date.now()}`, config, configPath: githubUrl.trim() });
      setShowAddModal(false);
      setGithubUrl('');
    } catch (e) {
      setAddError(`GitHub import failed: ${e}`);
    } finally {
      setAdding(false);
    }
  };

  const handleAddLocal = async () => {
    if (!localPath.trim()) return;
    setAdding(true);
    setAddError('');
    try {
      let config: DevPilotConfig;
      if (isTauri) {
        const { readConfig } = await import('../../../lib/bridge');
        config = await readConfig(localPath);
      } else {
        config = {
          schemaVersion: 1,
          project: {
            name: localPath.split('/').pop() ?? 'Project',
            root: localPath,
            defaultIDE: 'Cursor',
          },
          features: [],
          adapters: { ides: [], agents: [] },
        };
      }
      onAddProject({ id: `proj-${Date.now()}`, config, configPath: localPath });
      setShowAddModal(false);
      setLocalPath('');
    } catch (e) {
      setAddError(`Failed to read config: ${e}`);
    } finally {
      setAdding(false);
    }
  };

  const handleGenerateReport = () => {
    const today = new Date().toLocaleDateString('zh-TW', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    const lines: string[] = [`# DevPilot Weekly Report — ${today}`, ''];

    for (const project of projects) {
      const { features } = project.config;
      const done = features.filter((f) => f.status === 'done');
      const inProgress = features.filter((f) => f.status === 'in_progress');
      const blocked = features.filter((f) => f.status === 'on_hold');
      lines.push(`## ${project.config.project.name}`, '');
      if (done.length) {
        lines.push('### ✅ 完成');
        done.forEach((f) => lines.push(`- [${f.id}] ${f.name}`));
        lines.push('');
      }
      if (inProgress.length) {
        lines.push('### 🔄 進行中');
        inProgress.forEach((f) => lines.push(`- [${f.id}] ${f.name} (${f.progress}%)`));
        lines.push('');
      }
      if (blocked.length) {
        lines.push('### 🚧 阻塞');
        blocked.forEach((f) =>
          lines.push(`- [${f.id}] ${f.name}${f.notes ? ` — ${f.notes}` : ''}`),
        );
        lines.push('');
      }
    }
    lines.push('---', `_Generated by DevPilot v0.1.0 — ${new Date().toISOString()}_`);
    setReportText(lines.join('\n'));
  };

  const handleCopyReport = async () => {
    await navigator.clipboard.writeText(reportText);
    setReportCopied(true);
    setTimeout(() => setReportCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-lg font-semibold uppercase tracking-[0.18em] text-stone-50">
            Projects
          </h1>
          <p className="mt-1 text-xs text-stone-400">
            {projects.length} project{projects.length !== 1 ? 's' : ''} loaded.
          </p>
          <p className="mt-1 text-xs text-emerald-200/80">
            Dashboard scope: {selectedDashboardProjectIds.length} selected
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleGenerateReport}
            className="inline-flex h-9 items-center gap-2 border border-stone-200/20 px-3 text-xs uppercase tracking-[0.14em] text-stone-200 hover:bg-white/5"
          >
            <BarChart3 size={14} />
            Weekly Report
          </button>
          <button
            onClick={() => setShowAddModal(true)}
            className="inline-flex h-9 items-center gap-2 bg-stone-100 px-3 text-xs font-medium uppercase tracking-[0.14em] text-[#071d1a] hover:bg-amber-100"
          >
            <Plus size={14} />
            Add Project
          </button>
        </div>
      </div>

      {/* Project List */}
      <div className="space-y-3">
        {projects.map((project) => {
          const { features } = project.config;
          const done = features.filter((f) => f.status === 'done').length;
          const blocked = features.filter((f) => f.status === 'on_hold').length;
          const inProgress = features.filter((f) => f.status === 'in_progress').length;
          const isSelected = project.id === selectedProjectId;
          const isDashboardSelected = selectedDashboardProjectIds.includes(project.id);
          const projectRuns = runHistory.filter((r) => features.some((f) => f.id === r.featureId));

          return (
            <div
              key={project.id}
              className={`border bg-[#071d1a]/72 transition-colors ${
                isSelected
                  ? 'border-emerald-200/35'
                  : 'border-stone-200/18 hover:border-stone-200/30'
              }`}
            >
              <div
                className="flex cursor-pointer items-center justify-between px-4 py-3"
                onClick={() => onSelectProject(project.id)}
              >
                <div className="flex min-w-0 items-center gap-3">
                  <input
                    type="checkbox"
                    checked={isDashboardSelected}
                    onChange={(e) => onToggleDashboardProject(project.id, e.target.checked)}
                    onClick={(e) => e.stopPropagation()}
                    className="h-4 w-4 cursor-pointer accent-emerald-400"
                    title="Include this project in Dashboard"
                  />
                  <FolderGit2
                    size={16}
                    className={isSelected ? 'text-emerald-300' : 'text-stone-400'}
                  />
                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-stone-100">
                        {project.config.project.name}
                      </span>
                      {isDashboardSelected && (
                        <span className="border border-cyan-200/30 px-1.5 py-0.5 text-[10px] uppercase tracking-[0.16em] text-cyan-200">
                          Dashboard
                        </span>
                      )}
                    </div>
                    <p className="mt-0.5 max-w-sm truncate text-xs text-stone-500">
                      {project.config.project.root}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Weekly Report */}
      {reportText && (
        <div className="border border-stone-200/18 bg-[#071d1a]/72">
          <div className="flex items-center justify-between border-b border-stone-200/12 px-4 py-3">
            <h2 className="text-sm font-medium uppercase tracking-[0.16em] text-stone-100">
              Weekly Report
            </h2>
            <div className="flex gap-2">
              <button
                onClick={handleCopyReport}
                className={`px-3 py-1.5 text-xs font-medium transition-colors ${
                  reportCopied ? 'text-emerald-300' : 'text-stone-300 hover:text-stone-100'
                }`}
              >
                {reportCopied ? '✓ Copied' : 'Copy Markdown'}
              </button>
              <button
                onClick={() => setReportText('')}
                className="text-stone-400 hover:text-stone-100"
              >
                <X size={14} />
              </button>
            </div>
          </div>
          <pre className="max-h-96 overflow-auto whitespace-pre-wrap p-4 font-mono text-xs leading-5 text-stone-300">
            {reportText}
          </pre>
        </div>
      )}

      {/* Add Project Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-4 backdrop-blur-sm">
          <div className="w-full max-w-lg border border-stone-200/18 bg-[#071d1a] shadow-2xl">
            <div className="flex items-center justify-between border-b border-stone-200/12 bg-white/[0.035] px-6 py-4">
              <h3 className="text-lg font-bold text-stone-50">Add Project</h3>
              <button
                onClick={() => setShowAddModal(false)}
                className="text-2xl leading-none text-stone-400 hover:text-stone-100"
              >
                &times;
              </button>
            </div>
            <div className="space-y-4 p-6">
              {/* Mode tabs */}
              <div className="flex border border-stone-200/18">
                {(
                  [
                    { id: 'local', label: 'Local Path', icon: FolderOpen },
                    { id: 'github', label: 'GitHub URL', icon: Github },
                  ] as const
                ).map(({ id, label, icon: Icon }) => (
                  <button
                    key={id}
                    onClick={() => setAddMode(id)}
                    className={`flex flex-1 items-center justify-center gap-2 py-2 text-xs uppercase tracking-[0.14em] transition-colors ${
                      addMode === id
                        ? 'bg-stone-100 text-[#071d1a]'
                        : 'text-stone-300 hover:bg-white/5'
                    }`}
                  >
                    <Icon size={13} />
                    {label}
                  </button>
                ))}
              </div>

              {addMode === 'local' ? (
                <div className="space-y-2">
                  <label className="block text-sm font-medium text-stone-200">
                    Path to .dev-pilot.json
                  </label>
                  <input
                    value={localPath}
                    onChange={(e) => setLocalPath(e.target.value)}
                    placeholder="/path/to/project/.dev-pilot.json"
                    className="w-full border border-stone-200/20 bg-[#03100f] px-3 py-2 font-mono text-sm text-stone-100 outline-none focus:ring-2 focus:ring-emerald-300/35"
                  />
                  {!isTauri && (
                    <p className="text-[11px] text-amber-100/60">
                      Dev mode: creates a placeholder project. Real file reading requires Tauri.
                    </p>
                  )}
                </div>
              ) : (
                <div className="space-y-3">
                  <div>
                    <label className="mb-1 block text-sm font-medium text-stone-200">
                      GitHub Repository URL
                    </label>
                    <input
                      value={githubUrl}
                      onChange={(e) => setGithubUrl(e.target.value)}
                      placeholder="https://github.com/user/my-app"
                      className="w-full border border-stone-200/20 bg-[#03100f] px-3 py-2 font-mono text-sm text-stone-100 outline-none focus:ring-2 focus:ring-emerald-300/35"
                    />
                  </div>
                  <div>
                    <label className="mb-1 block text-sm font-medium text-stone-200">
                      GitHub Token
                    </label>
                    <input
                      type="password"
                      value={githubToken}
                      onChange={(e) => {
                        setGithubToken(e.target.value);
                        localStorage.setItem('devpilot-github-token', e.target.value);
                      }}
                      placeholder="ghp_..."
                      className="w-full border border-stone-200/20 bg-[#03100f] px-3 py-2 font-mono text-sm text-stone-100 outline-none focus:ring-2 focus:ring-emerald-300/35"
                    />
                  </div>
                  <p className="text-[11px] text-amber-100/60">
                    GitHub import requires Tauri bridge + GitHub GraphQL API. PR/issue analysis and
                    smart alerts will be enabled when connected.
                  </p>
                </div>
              )}

              {addError && <p className="text-sm text-red-400">{addError}</p>}
            </div>
            <div className="flex justify-end gap-3 border-t border-stone-200/12 bg-white/[0.035] px-6 py-4">
              <button
                onClick={() => setShowAddModal(false)}
                className="px-4 py-2 text-sm text-stone-300 hover:bg-white/5"
              >
                Cancel
              </button>
              <button
                onClick={addMode === 'local' ? handleAddLocal : handleAddGitHub}
                disabled={
                  adding ||
                  (addMode === 'local' ? !localPath.trim() : !githubUrl.trim() || !isTauri)
                }
                className="bg-stone-100 px-4 py-2 text-sm font-medium text-[#071d1a] hover:bg-amber-100 disabled:cursor-not-allowed disabled:opacity-40"
              >
                {adding
                  ? 'Importing…'
                  : addMode === 'github'
                    ? isTauri
                      ? 'Import from GitHub'
                      : 'Requires Tauri'
                    : 'Add Project'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
